---
title: "MovieRecoNeel"
author: "Kartik Lal"
date: "12/1/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library('ggplot2')
library('tidyverse')
library('dplyr')
library('splitstackshape')
library(dummies)
library(tidytext)
library(stringr)
library(shiny)
library(shinydashboard)
library(DT)
library(shinyWidgets)
library(shinythemes)

```

```{r loading data}
ratings <- read_csv("C:/Users/karti/Desktop/Kartik/Masters_NEU/Semester 1/Introduction to DM/Project/Data/ratings.csv")

movies <- read_csv("C:/Users/karti/Desktop/Kartik/Masters_NEU/Semester 1/Introduction to DM/Project/Data/movies.csv")

```


```{r user filter}
userList <- ratings %>% select(userId) %>%  
  unique() %>% head(10000)

movies_new <- movies[!duplicated(movies$title),]

movies_split <- movies_new %>% 
  cSplit('genres', '|', 'long') 

ratingsMovies <- 
  userList %>% inner_join(ratings) %>%
  left_join(movies_split) %>%
  select(-timestamp)

```



```{r Cast DTM and IBCF}
### Using CAST DTM

genre_list <- movies %>% 
  cSplit('genres', '|', 'long') %>% 
  select(genres) %>% 
  distinct(genres)

movies_new <- movies[!duplicated(movies$title),]
userList <- ratings %>% select(userId) %>%  
  unique() %>% head(10000)

movies_split <- movies_new %>% 
  cSplit('genres', '|', 'long') 

ratingsMovies <- 
  userList %>% inner_join(ratings) %>%
  left_join(movies_split) 

cf_matrix<- ratingsMovies %>%   
  #filter(genres == "Thriller") %>% 
  select('userId','title','rating') %>% 
  cast_dtm(userId,title,rating)


ibcf_matrix <- cf_matrix %>% 
  as.matrix() %>% 
  as.data.frame()



```

```{r Calculate correlation}
cor_values<-ibcfMatrix %>% 
  cor(ibcfMatrix$`Superman (1978)`,use="pairwise.complete.obs") 

final_matrixIBCF <-tibble(colnames(ibcfMatrix), cor_values) %>% 
  left_join(movies_new,by=c(`colnames(ibcfMatrix)`="title"))

```

```{r UBCF creation}

ubcfMatrix <- t(ibcfMatrix)


#view(ubcfMatrix %>% head(5))
#ubcfMatrix$user= rownames(ubcfMatrix)
```

```{r UBCF correlations}
#view(ubcfMatrix%>% head(10))

cor_values<-ubcfMatrix %>% 
  cor(ubcfMatrix[,26],use="pairwise.complete.obs") 

final_matrixUBCF <-tibble(colnames(ubcfMatrix), cor_values) %>% 
  rename("userId"=`colnames(ubcfMatrix)`)

```

```{r UBCF Movie Recommendation}

### Select the 4 most similar users
ubcfSelectUsers <- 
  final_matrixUBCF[order(-cor_values),] %>% head(4)

### Add userId as a column
tempUsers <- cbind(userId= rownames(ibcfMatrix),ibcfMatrix)

### Random Error- May fail later
tempUsers <- tempUsers[,-c(2886)]

### Join with IBCF
tempUserSelectIbcf <- tempUsers %>%
  filter(userId %in% ubcfSelectUsers$userId)

### Add userId as the rownames
rownames(tempUserSelectIbcf) <- tempUserSelectIbcf$userId 

### Transpose and add movies as a column
tempTransposeUserIbcf <- tempUserSelectIbcf %>% select(-c(userId)) %>% t()

MoviesSimilarUsers <- cbind(title= rownames(tempTransposeUserIbcf),tempTransposeUserIbcf)

MoviesSimilarUsers <- MoviesSimilarUsers %>% as.data.frame()

### Select those movies which have not been seen by the selected user and 
### seen by atleast one of the similar users

MoviesRecommendUbcf <- MoviesSimilarUsers %>% 
  filter(`26` == 0, MoviesSimilarUsers[,3]!=0 | MoviesSimilarUsers[,4]!=0 |
           MoviesSimilarUsers[,5]!=0)

view(MoviesSimilarUsers %>% filter(`5`!=0) %>%left_join(movies) %>%
       select(title,genres))

### Add their ratings, and take the top 10 movies as per the ratings' sum

MoviesRecommend <- view(MoviesRecommendUbcf %>% 
  mutate(movieScore = as.numeric(levels(MoviesRecommendUbcf[,3])[MoviesRecommendUbcf[,3]]) +
           as.numeric(levels(MoviesRecommendUbcf[,4])[MoviesRecommendUbcf[,4]])+
           as.numeric(levels(MoviesRecommendUbcf[,5])[MoviesRecommendUbcf[,5]])) %>%
  arrange(desc(movieScore)) %>% head(10) %>% rename(`Movie`= title)) %>%
  select(`Movie`)

MoviesRecommend2 <- 
  view(MoviesRecommendUbcf %>% 
  mutate(movieScore = as.numeric(levels(MoviesRecommendUbcf[,3])[MoviesRecommendUbcf[,3]]) +
           as.numeric(levels(MoviesRecommendUbcf[,4])[MoviesRecommendUbcf[,4]])+
           as.numeric(levels(MoviesRecommendUbcf[,5])[MoviesRecommendUbcf[,5]])) %>%
  arrange(desc(movieScore)) %>% head(10) %>%
  left_join(movies))
  


### These 10 movies are recommended as per user based collaborative filtering
print(MoviesRecommend)

```

```{r Build Test Case}

### Select those movies which have not been seen by the selected user and 
### seen by atleast one of the similar users

MoviesRecommendUbcfValidate <- MoviesSimilarUsers %>% 
  filter(`26` != 0, MoviesSimilarUsers[,3]!=0 | MoviesSimilarUsers[,4]!=0 |
           MoviesSimilarUsers[,5]!=0)

MoviesRecommendUbcfValidate[MoviesRecommendUbcfValidate == 0] <- NA

MoviesRecommendUbcfValidate<- MoviesRecommendUbcfValidate %>% mutate(
  userActualRating= as.numeric(levels(MoviesRecommendUbcfValidate[,2])[MoviesRecommendUbcfValidate[,2]]),
  user1= as.numeric(levels(MoviesRecommendUbcfValidate[,3])[MoviesRecommendUbcfValidate[,3]]),
  user2= as.numeric(levels(MoviesRecommendUbcfValidate[,4])[MoviesRecommendUbcfValidate[,4]]),
  user3= as.numeric(levels(MoviesRecommendUbcfValidate[,5])[MoviesRecommendUbcfValidate[,5]]))

MovieRecoPredRating <- MoviesRecommendUbcfValidate %>% mutate(
  predictedRating=rowMeans(MoviesRecommendUbcfValidate[,7:9],na.rm = TRUE)) %>%
  select(-c(2:5),-c(7:9))

MovieRecoPredRating <- MovieRecoPredRating %>% mutate(`How did the user rate the movie?`= 
                                 ifelse(userActualRating>=3.5,"Good","Bad"),
                               `Prediction: Will the user like the movie?`=ifelse(predictedRating>=3.5,"Good","Bad")) %>%
  mutate(Error=ifelse(`How did the user rate the movie?`!=`Prediction: Will the user like the movie?`,1,0)) 

MovieRecoPredRating

MovieRecoPredRating %>%
  summarise(Accuracy=1-(sum(Error)/n()))


```

```{r Read the evaluation file}

MovieRecoPredRating <- read_csv("C:/Users/karti/Desktop/Kartik/Masters_NEU/Semester 1/Introduction to DM/Project/evaluation.csv")

MovieRecoPredRating

```

```{r Write CSV}
write.csv(MovieRecoPredRating,"C:/Users/karti/Desktop/Kartik/Masters_NEU/Semester 1/Introduction to DM/Project/evaluation.csv", row.names = FALSE)

```

